name: coin-lowrank
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - numpy
  - matplotlib
  - pillow
  - tqdm
  - pip
  - pip:
      - constriction
